spring.application.name=gateway-service

server.port=8080

# Matricula
spring.cloud.gateway.routes[0].id=matricula-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/matriculas/**

# Avaliacao
spring.cloud.gateway.routes[1].id=avaliacao-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/avaliacoes/**

# Curso
spring.cloud.gateway.routes[2].id=curso-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/cursos/**

# Disciplina
spring.cloud.gateway.routes[3].id=disciplina-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/disciplinas/**

# Pessoa
spring.cloud.gateway.routes[4].id=pessoa-service
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/pessoas/**

# Professor
spring.cloud.gateway.routes[5].id=professor-service
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/professores/**

# Turma
spring.cloud.gateway.routes[6].id=turma-service
spring.cloud.gateway.routes[6].uri=http://localhost:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/turmas/**
