services:

  matricula-service:
    build: ./microservicos/matricula-service
    ports:
      - "8081:8081"

  avaliacao-service:
    build: ./microservicos/avaliacao-service
    ports:
      - "8082:8082"

  curso-service:
    build: ./microservicos/curso-service
    ports:
      - "8083:8083"

  disciplina-service:
    build: ./microservicos/disciplina-service
    ports:
      - "8084:8084"

  pessoa-service:
    build: ./microservicos/pessoa-service
    ports:
      - "8085:8085"

  professor-service:
    build: ./microservicos/professor-service
    ports:
      - "8086:8086"

  turma-service:
    build: ./microservicos/turma-service
    ports:
      - "8087:8087"

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"